name: Deploy to EC2 frontEnd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommercedenti:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Detén el servicio actual
          sudo systemctl stop ecommercedenti.service || true

          # Actualiza la imagen desde Docker Hub
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommercedenti:latest

          # Elimina el contenedor anterior (si existe)
          docker stop ecommercedenti || true
          docker rm ecommercedenti || true

          # Inicia el servicio con la nueva imagen
          sudo systemctl start ecommercedenti.service
          